#!/bin/bash -e

case "$DEITY" in
   Jehovah)
      cat <<'EOT'
Our Father in origin,
   hallowed be your ref.
May your commits come soon,
   and may your pull requests be merged,
   on master as it is in origin/master.
Give us today our daily SHAs,
   and forgive us our push -fs
   as we have forgiven those who push -f against us.
Lead us not into Subversion,
   but deliver us from detached HEAD.
For yours is the source code, and the power, and the glory, forever.
Amen.
EOT
      ;;
   'Kwisatz Haderach')
      cat <<'EOT'
I must not rebase.
Rebasing is the commit-killer.
Rebasing is the little-death that brings total squashing.
I will face my rebasing.
I will permit it to pass over my commits and pick my commits.
And when it has gone past I will turn the inner log to see its path.
Where the rebasing has gone there will be nothing.
Only the tip will remain.
EOT
      ;;
   *)
      echo "\$DEITY not set.  You're on your own, bud."
      ;;
esac

